### ISSUE TITLE
Ручное заполнение ПДФ вместо OCR

### ISSUE THREAD

**Issue by ferrine** [emsch/femida#15]
После проверки, вечером, был тот самый случай, когда надо было вручную заполнять пропуски, в итоге мы потратили порядка часа полтора на 11 человек, сделали это в итоге не в базу, а в эксель. Хотелось бы видеть удобный интерфейс заполнения проблемных пдф.

**Comment by feriat** [comment]
Имхо #33 должно эту штуку порешать, @ferrine ? Если не справилась кропилка, то надо пересканировать или правда обрабатывать вручную. Чтобы обрабатывать manual можно использовать этот интерфейс.

**Comment by feriat** [comment]
Закрываю
