### ISSUE TITLE
Закрыть на пароль

### ISSUE THREAD

**Issue by feriat** [emsch/femida#16]
Можно силами apache, можно силами аутентификации

Главное: страницу загрузки, статуса, базы и распознавания не должны видеть люди в интернете свободно.

**Comment by ferrine** [comment]
Лучше тогда настроить группы пользователей

--
Max

сб, 22 сент. 2018 г., 23:32 Andrew <notifications@github.com>:

**Comment by feriat** [comment]
Спасибо
