### ISSUE TITLE
update test examples

### ISSUE THREAD

**Issue by ferrine** [emsch/femida#38]
- [ ] update test examples
- [ ] upload excel files to root directory `examples`

**Comment by ferrine** [comment]
https://github.com/emsch/femida/tree/master/frontend/app/static

**Comment by feriat** [comment]
Должна делаться вместе с #52

**Comment by feriat** [comment]
Давайте закрою как дубль: пример отсканенной pdf мне кажется не нужен, а в #52 мы сделали шаблон pdf с настраиваемой шапкой, который можно печатать. Туда же я залил эксельки, просто для бекапа: рекомендуется пользоваться pdf.
