### ISSUE TITLE
Прокрутка варианта

### ISSUE THREAD

**Issue by KaterinaLebedeva** [emsch/femida#4]
При написании варианта и прокрутки страницы, не страница прокручивается, а вариант. Это увеличивает количество ошибок при распознавании варианта. Для прокрутки страницы нужно отдельно тыкнуть в страницу. Исправьте, пожалуйста! 
![image](https://user-images.githubusercontent.com/43316207/45596792-51b2ba00-b9ca-11e8-8e68-18dde207e5a2.png)

**Comment by feriat** [comment]
Сделали в #39
