### ISSUE TITLE
Сломана ручка экспорта

### ISSUE THREAD

**Issue by feriat** [emsch/femida#5]

**Comment by feriat** [comment]
Дело в https://github.com/emsch/femida/blob/master/frontend/app/export.py#L141
Надо убрать raise

**Comment by feriat** [comment]
@ferrine Макс, тикет ещё актуален?

**Comment by ferrine** [comment]
Да

--
Max

ср, 26 сент. 2018 г., 9:39 Andrew <notifications@github.com>:
