### ISSUE TITLE
Нет гугл почты

### ISSUE THREAD

**Issue by feriat** [emsch/femida#51]
_issue со встречи 2019-01-16_

Что делать, если у проверяющего нет гугловой почты?

**Comment by dima9703** [comment]
Договорились закрыть этот issue, поскольку делать это долго, т.к.:
1. Придется усложнить логику базы (хранить какого пользователя где авторизовывать)
2. Делать разные способы обработки oauth разных систем
3.  Делать интерфейс

С продуктовой части проблема не выглядит критичной, т.к. можно выдать произвольному человеку логин и пароль вида SMTH@emsch.ru, с помощью которой можно авторизоваться.
